trigger: none

pool:
  vmImage: 'windows-latest'

steps:

- task: XplatGenerateReleaseNotes@3
  inputs:
    outputfile: '''$(Build.ArtifactStagingDirectory)\ReleaseNotes_$(build.buildnumber).md'''
    templateLocation: 'InLine'
    inlinetemplate: |
      ## Build Number: {{buildDetails.id}}
      
      {{forEach commits}} {{if isFirst}} Associated commits {{/if}}
      
      ** ID {{this.id}} **
      Message: {{this.message}}
      Commited by: {{this.author.displayName}} 
      {{/forEach}}
      
      {{forEach workItems}} {{if isFirst}} Associated Work Items {{/if}}
      
      ** {{this.id}} {{lookup this.fields 'System.Title'}} **
      Type {{lookup this.fields 'System.WorkItemType'}}
      Tags {{lookup this.fields 'System.Tags'}}
      Assigned {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}} 
      
      {{/forEach}}
    sortWi: true
    dumpPayloadToConsole: false
    dumpPayloadToFile: false
    replaceFile: True
    getParentsAndChildren: False
    getAllParents: False
    getIndirectPullRequests: False

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\ReleaseNotes_$(build.buildnumber).md'
    ArtifactName: 'drop'
    publishLocation: 'Container'
