trigger: none

pool:
  vmImage: 'windows-latest'

steps:

- task: XplatGenerateReleaseNotes@3
  inputs:
    outputfile: '$(Build.ArtifactStagingDirectory)\ReleaseNotes_$(build.buildnumber).md'
    templateLocation: 'File'
    templatefile: 'template-release-notes.md'
    sortWi: true
    dumpPayloadToConsole: false
    dumpPayloadToFile: false
    replaceFile: true
    getParentsAndChildren: false
    getAllParents: false
    getIndirectPullRequests: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\ReleaseNotes_$(build.buildnumber).md'
    ArtifactName: 'drop'
    publishLocation: 'Container'

#- task: WikiUpdaterTask@1
#  inputs:
#    repo: 'https://github.com/Cloud-Awesome/CloudAwesome.Xrm.Customisation.Sandbox'
#    branch: 'master'
#    filename: 'documentation/ReleaseNotes_$(build.buildnumber).md'
#    replaceFile: true
#    dataIsFile: true
#    sourceFile: '$(Build.ArtifactStagingDirectory)\ReleaseNotes_$(build.buildnumber).md'
#    message: 'Release notes for Build $(build.buildnumber)'
#    gitname: 'Azure Pipelines'
#    gitemail: 'azure-pipelines@cloudawesome.uk'
#    useAgentToken: true
#    localpath: '$(System.DefaultWorkingDirectory)\repo'
