trigger: none

pool:
  vmImage: 'windows-latest'

steps:

- task: XplatGenerateReleaseNotes@3
  inputs:
    outputfile: '''$(Build.ArtifactStagingDirectory)\ReleaseNotes_$(build.buildnumber).md'''
    templateLocation: 'File'
    templatefile: 'template-release-notes.md'
    sortWi: true
    dumpPayloadToConsole: false
    dumpPayloadToFile: false
    replaceFile: true
    getParentsAndChildren: false
    getAllParents: false
    getIndirectPullRequests: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\ReleaseNotes_$(build.buildnumber).md'
    ArtifactName: 'drop'
    publishLocation: 'Container'
