trigger: none

pool:
  vmImage: 'windows-latest'

steps:

- task: XplatGenerateReleaseNotes@3
  inputs:
    outputfile: '''$(Build.ArtifactStagingDirectory)\ReleaseNotes_$(build.buildnumber).md'''
    templateLocation: 'InLine'
    inlinetemplate: |
      # Release notes for build $(Build.DefinitionName)
      **Build Number**  : $($build.buildnumber)
      **Build started** : $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.startTime)
      **Source Branch** : $($build.sourceBranch)
      ### Associated work items
      @@WILOOP@@
      * **$($widetail.fields.'System.WorkItemType') $($widetail.id)** [Assigned by: $($widetail.fields.'System.AssignedTo')]     $($widetail.fields.'System.Title')
      @@WILOOP@@
      ### Associated change sets/commits
      @@CSLOOP@@
      * **ID $($csdetail.changesetid)$($csdetail.commitid)** $($csdetail.comment)
      @@CSLOOP@@
    sortWi: true
    dumpPayloadToConsole: false
    dumpPayloadToFile: false
    replaceFile: True
    getParentsAndChildren: False
    getAllParents: False
    getIndirectPullRequests: False

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\ReleaseNotes_$(build.buildnumber).md'
    ArtifactName: 'drop'
    publishLocation: 'Container'
